name: Build & Release Qt6 Calculator (Ubuntu)

on:
  push:
    tags:
      - 'v*'  # Runs when version tags are pushed (e.g., v1.0)

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: Build Linux Executable
        run: |
          pyinstaller --onefile --windowed --icon=src/icon.png --add-data "src/calculatorui.ui:src" src/calculator.py

      - name: Upload Linux Build Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: dist/calculator
          tag_name: ${{ github.ref }}
          token: ${{ secrets.GH_TOKEN }}