name: Build & Release Qt6 Calculator

on:
  push:
    tags:
      - 'v*'  # Runs when version tags are pushed (e.g., v1.0)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed --icon=src/icon.ico --add-data "src/calculatorui.ui:src" src/calculator.py

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ github.ref }}