name: Parallel Builds

on:
  push:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      # [Same build steps as above]
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: windows-${{ github.sha }}
          release_name: Windows Build (${{ github.sha }})
          files: dist/*.exe

  linux:
    runs-on: ubuntu-latest
    steps:
      # [Same build steps as above]
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: linux-${{ github.sha }}
          release_name: Linux Build (${{ github.sha }})
          files: dist/*